const projetos = [
    { titulo: "Conecta Comunidade", descricao: "Oficinas e ações de inclusão digital para aproximar pessoas da tecnologia e do conhecimento.", imagem: "../imagens/projeto-conecta.svg", alt: "Ilustração de uma atividade de inclusão digital.", categorias: ["Inclusão digital", "Capacitação"], itens: ["Inclusão digital", "Capacitação", "Acesso à informação"] },
    { titulo: "Aprender para Crescer", descricao: "Ações de apoio educacional destinadas a crianças e jovens em situação de vulnerabilidade.", imagem: "../imagens/projeto-aprender.svg", alt: "Ilustração relacionada a uma atividade educacional.", categorias: ["Educação", "Leitura"], itens: ["Reforço educacional", "Leitura", "Desenvolvimento pessoal"] },
    { titulo: "Rede do Bem", descricao: "Mobilização de voluntários e parceiros para ações comunitárias e campanhas solidárias.", imagem: "../imagens/projeto-rede.svg", alt: "Ilustração de colaboração entre participantes de uma ação comunitária.", categorias: ["Voluntariado", "Parcerias"], itens: ["Voluntariado", "Campanhas", "Parcerias"] }
];

function gerarProjetos(dados) {
    return dados.map(projeto => `<article class="project-card"><img src="${projeto.imagem}" alt="${projeto.alt}"><div class="project-body"><ul class="badge-list" aria-label="Categorias do projeto">${projeto.categorias.map(categoria => `<li><span class="badge">${categoria}</span></li>`).join("")}</ul><h3>${projeto.titulo}</h3><p>${projeto.descricao}</p><ul>${projeto.itens.map(item => `<li>${item}</li>`).join("")}</ul></div></article>`).join("");
}
function renderizarInicio() {
    return `<section class="hero" aria-labelledby="titulo-inicio"><div class="container hero-grid"><div class="hero-copy"><p class="eyebrow">Instituto Viver Melhor</p><h1 id="titulo-inicio">Solidariedade que transforma oportunidades em mudanças reais.</h1><p>Conectamos pessoas, conhecimento e ações comunitárias para promover inclusão e fortalecer comunidades.</p><div class="hero-actions"><a class="button" href="#projetos" data-route="projetos">Conheça nossos projetos</a><a class="button button-secondary" href="#cadastro" data-route="cadastro">Quero participar</a></div></div><figure class="hero-media"><img src="../imagens/hero-ong.svg" alt="Ilustração de pessoas participando de uma ação comunitária."><figcaption>Conectando pessoas para construir oportunidades.</figcaption></figure></div></section><section class="section" aria-labelledby="sobre-titulo"><div class="container two-columns"><div><p class="eyebrow">Quem somos</p><h2 id="sobre-titulo">Uma rede de pessoas que acredita no poder da colaboração</h2></div><div><p>O Instituto Viver Melhor desenvolve iniciativas voltadas à inclusão digital, educação e mobilização comunitária.</p><p>Nosso trabalho busca aproximar voluntários, doadores e parceiros de projetos que geram oportunidades.</p></div></div></section><section class="section section-alt" aria-labelledby="contato-titulo"><div class="container two-columns"><div><p class="eyebrow">Fale conosco</p><h2 id="contato-titulo">Entre em contato</h2><p>Para saber mais sobre nossas ações ou conversar sobre parcerias, utilize nossos canais.</p></div><address class="contact-card"><p><strong>E-mail:</strong> contato@institutovivermelhor.org</p><p><strong>Telefone:</strong> (11) 4000-0000</p><p><strong>Atendimento:</strong> segunda a sexta, das 9h às 17h.</p></address></div></section>`;
}
function renderizarProjetos() {
    return `<section class="page-header" aria-labelledby="titulo-projetos"><div class="container"><p class="eyebrow">Iniciativas solidárias</p><h1 id="titulo-projetos">Projetos que geram oportunidades</h1><p>Conheça algumas das iniciativas do Instituto Viver Melhor e descubra como contribuir.</p></div></section><section class="section" aria-labelledby="projetos-titulo"><div class="container"><h2 id="projetos-titulo">Nossos projetos sociais</h2><div class="cards" id="lista-projetos">${gerarProjetos(projetos)}</div></div></section><section class="section" aria-labelledby="grafico-titulo"><div class="container chart-section"><div class="chart-intro"><p class="eyebrow">Visão geral</p><h2 id="grafico-titulo">Áreas principais das iniciativas</h2><p>Este gráfico apresenta, de forma visual, uma área principal associada a cada projeto do Instituto.</p></div><div class="chart-container"><canvas id="grafico-projetos" aria-label="Gráfico das áreas principais das iniciativas" role="img"></canvas><p class="chart-fallback">O gráfico depende do carregamento da biblioteca de visualização. As informações dos projetos continuam disponíveis nas seções acima.</p></div></div></section><section class="section section-alt" aria-labelledby="doacao-titulo"><div class="container narrow"><h2 id="doacao-titulo">Como contribuir</h2><p>Você pode apoiar nossas iniciativas por meio de doações, voluntariado ou parcerias.</p><div class="action-grid"><article class="mini-card"><h3>Doação</h3><p>Contribua financeiramente para apoiar a continuidade das ações sociais.</p></article><article class="mini-card"><h3>Voluntariado</h3><p>Ofereça seu tempo e suas habilidades para colaborar com nossas iniciativas.</p></article><article class="mini-card"><h3>Parceria</h3><p>Junte-se ao Instituto para desenvolver ações e oportunidades em conjunto.</p></article></div><a class="button" href="#cadastro" data-route="cadastro">Quero participar</a></div></section>`;
}
function renderizarCadastro() {
    return `<section class="page-header" aria-labelledby="titulo-cadastro"><div class="container"><p class="eyebrow">Engajamento</p><h1 id="titulo-cadastro">Faça parte da nossa rede</h1><p>Preencha o formulário para demonstrar interesse em participar das iniciativas do Instituto Viver Melhor.</p></div></section><section class="section" aria-labelledby="formulario-titulo"><div class="container form-container"><div class="form-intro"><h2 id="formulario-titulo">Cadastro de colaborador</h2><p>Os campos marcados com <span aria-hidden="true">*</span> são obrigatórios.</p></div><form id="cadastroForm" action="#" method="post"><fieldset><legend>Dados pessoais</legend><div class="form-grid"><div class="field full"><label for="nome">Nome completo *</label><input type="text" id="nome" name="nome" required minlength="3"></div><div class="field"><label for="cpf">CPF *</label><input type="text" id="cpf" name="cpf" required inputmode="numeric" placeholder="000.000.000-00" pattern="\d{3}\.\d{3}\.\d{3}-\d{2}"></div><div class="field"><label for="telefone">Telefone *</label><input type="tel" id="telefone" name="telefone" required placeholder="(00) 00000-0000"></div><div class="field"><label for="email">E-mail *</label><input type="email" id="email" name="email" required></div><div class="field"><label for="cep">CEP *</label><input type="text" id="cep" name="cep" required inputmode="numeric" placeholder="00000-000" pattern="\d{5}-\d{3}"></div><div class="field"><label for="interesse">Área de interesse *</label><select id="interesse" name="interesse" required><option value="">Selecione</option><option>Voluntariado</option><option>Doação</option><option>Parceria</option></select></div><div class="field full"><label for="mensagem">Conte-nos como gostaria de ajudar</label><textarea id="mensagem" name="mensagem" rows="5" maxlength="500"></textarea></div><div class="checkbox-field full"><input type="checkbox" id="consentimento" required><label for="consentimento">Declaro que as informações fornecidas são verdadeiras e concordo com o contato da organização. *</label></div></div></fieldset><div class="form-actions"><button class="button" type="submit">Enviar cadastro</button><button class="button button-secondary" type="reset">Limpar formulário</button></div><p id="formStatus" class="form-status" role="status" aria-live="polite"></p></form></div></section>`;
}
let graficoProjetos = null;
function inicializarGraficoProjetos() {
    const canvas = document.getElementById("grafico-projetos");
    if (!canvas || typeof Chart === "undefined") return;
    if (graficoProjetos) graficoProjetos.destroy();
    const labels = projetos.map(projeto => projeto.titulo);
    const dados = projetos.map(projeto => projeto.categorias.length);
    const movimentoReduzido = window.matchMedia("(prefers-reduced-motion: reduce)").matches;
    graficoProjetos = new Chart(canvas, { type: "bar", data: { labels, datasets: [{ label: "Áreas de atuação por projeto", data: dados, borderWidth: 1 }] }, options: { responsive: true, maintainAspectRatio: false, animation: movimentoReduzido ? false : undefined, plugins: { legend: { display: true } }, scales: { y: { beginAtZero: true, ticks: { stepSize: 1 } } } } });
}
IVM = window.IVM || {};
IVM.projetos = { dados: projetos, gerar: gerarProjetos, inicio: renderizarInicio, projetos: renderizarProjetos, cadastro: renderizarCadastro, grafico: inicializarGraficoProjetos };
